first commit
nishitatsu-dev/ruby-practices pull request #1
Opened 2021-07-30 06:42 UTC by nishitatsu-dev

FizzBuzz問題の課題を作成しました。ご確認お願いします。

2021-08-03 17:25 UTC, komagata requested changes

2021-08-03 17:25 UTC, komagata commented on 01.fizzbuzz/fizzbuzz.rb
> +20.times do
```suggestion
20.times do |i|
```

timesメソッドは上記のようにブロック引数を追加すると1行目の変数定義と1を足す処理が不要になりますのでそのあたりを調べてみてください～

2021-08-04 06:35 UTC, nishitatsu-dev commented on 01.fizzbuzz/fizzbuzz.rb
> +20.times do
ありがとうございます。
「ブロック引数を追加」バージョンに変更しました。ご確認お願いします。
（前のバージョンは、コメントアウトして残しています。）

2021-08-04 08:39 UTC, komagata commented on 01.fizzbuzz/fizzbuzz.rb
> +20.times do
バージョン管理システムを使っているので基本的にコメントアウトして古いコードを残すことはしないようにするといいかもです。

また例えば

`(1..20).each do |i|`

のようにRangeオブジェクトとeachを使うと`+1`しなくていいのでわかりやすいコードになります。

2021-08-04 15:03 UTC, nishitatsu-dev commented on 01.fizzbuzz/fizzbuzz.rb
> +20.times do
ありがとうございます。
下記２点、変更しました。ご確認お願いします。
１）「`.each`メソッド」バージョンに変更しました。
２）不要な記述を削除しました。
よろしくお願い致します。

2021-08-05 11:09 UTC, komagata requested changes
条件式にカッコは不要です～

2021-08-05 11:09 UTC, komagata commented on 01.fizzbuzz/fizzbuzz.rb
> +  if (i % (3 * 5)) == 0
```suggestion
  if i % (3 * 5) == 0
```

2021-08-05 11:09 UTC, komagata commented on 01.fizzbuzz/fizzbuzz.rb
> +  elsif (i % 3) == 0
```suggestion
  elsif i % 3 == 0
```

2021-08-05 11:09 UTC, komagata commented on 01.fizzbuzz/fizzbuzz.rb
> +  elsif (i % 5) == 0
```suggestion
  elsif i % 5 == 0
```

2021-08-05 15:38 UTC, nishitatsu-dev commented on 01.fizzbuzz/fizzbuzz.rb
> +  elsif (i % 5) == 0
ありがとうございます。
上記３箇所の不要カッコ削除バージョンを作成しました。
度々すみませんが、ご確認お願いします。

2021-08-06 21:00 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂

2021-08-07 02:32 UTC, merged

2021-08-07 02:33 UTC, nishitatsu-dev commented
ありがとうございました！！！