「lsコマンド〜オブジェクト指向版」の初版を作成しました。
nishitatsu-dev/ruby-practices pull request #11
Opened 2023-04-17 07:28 UTC by nishitatsu-dev

「lsコマンド〜オブジェクト指向版」の初版を作成しました。レビューをお願いします。

2023-04-23 16:03 UTC, u1tnk reviewed
formatterあたり見ると基本的なオブジェクト指向は分かっていそうですね 👍 
あとはファイル情報クラスを利用するところと、
ネーミングや細かいところをブラッシュアップすると良いと思います 💪

2023-04-23 16:03 UTC, u1tnk commented on 08.ls_object/form_opt_l.rb
> +  FILE_MODE = { '7' => 'rwx', '6' => 'rw-', '5' => 'r-x', '4' => 'r--', '3' => '-wx', '2' => '-w-', '1' => '--x', '0' => '---' }.freeze
細かいですが、 一ペア一行の方が見やすいし編集もしやすいと思います。

2023-04-23 16:03 UTC, u1tnk commented on 08.ls_object/form_opt_l.rb
> +      state = File.lstat(file)
ちょっとここらへんは煩雑になってしまっていますね。ファイル情報をまとめて管理するオブジェクトが居るともう少しすっきりすると思います。

2023-04-24 08:50 UTC, nishitatsu-dev commented on 08.ls_object/ls_oo.rb
> +class LSManager
Managerを削除し、LSのみとしました。

2023-04-24 08:51 UTC, nishitatsu-dev commented on 08.ls_object/ls_oo.rb
> +  def self.run_ls(argv, options)
lsを削除し、runのみとしました。

2023-04-24 08:52 UTC, nishitatsu-dev commented on 08.ls_object/form_opt_l.rb
> +class FormOptL
`FormOptionLong`としました。

2023-04-24 08:55 UTC, nishitatsu-dev commented on 08.ls_object/form_opt_l.rb
> +      state = File.lstat(file)
ファイル情報クラスを追加し、関連部分を書き直しました。

2023-04-24 16:33 UTC, u1tnk requested changes

2023-04-24 16:33 UTC, u1tnk commented on 08.ls_object/form_opt_l.rb
> +class FormOptionLong
クラス名だけ変わってファイル名が変わっていませんので合わせるようにしましょう。
また、前回指摘漏れましたが FormはFormatの略称でしょうか？でしたら同様です。
またクラス名は基本は名詞なのでFormatで始まるより、Formatterで終わる方が良いですね

2023-04-24 16:33 UTC, u1tnk commented on 08.ls_object/file_details.rb
> +class FileDetails
Detailsだとだとファイルの詳細情報の配列が入っているクラスと思うので単数形が良いと思います。

2023-04-24 16:33 UTC, u1tnk commented on 08.ls_object/file_details.rb
> +    state = File.lstat(file)
残念ながらこれだとメソッドで分けたのと大差無いです。
stateのみを保持して、 例えば userだと `file_detail.user`で取れるようにできるとメソッド一つが短かくなってだいぶ読みやすくなると思います。

2023-04-25 03:44 UTC, nishitatsu-dev commented on 08.ls_object/form_opt_l.rb
> +class FormOptionLong
ファイル名と関連箇所を修正しました。

2023-04-25 03:44 UTC, nishitatsu-dev commented on 08.ls_object/file_details.rb
> +class FileDetails
単数形に修正しました。

2023-04-25 03:49 UTC, nishitatsu-dev commented on 08.ls_object/file_details.rb
> +    state = File.lstat(file)
`FileDetail`クラスを修正し、`OptionLongFormatter`クラスの関連部分も修正しました。

2023-04-26 03:47 UTC, u1tnk requested changes
FileDetailについてコメントしました。
ListProviderなどもそうですが、 attr_reader/accessorは便利ですが、まずは使わない方向で考えた方が良いですね。


 initializeで 「この情報さえあればなんでも取れる元データ」だけ最低限保存しておいて、あとは呼ばれたときに計算して返すメソッドを用意するのが基本です。
元データじゃなくて加工後のデータを保存すると他の形式が欲しくなったときに困りますし、両方保存するのは無駄だからです。
遅い処理だったり頻繁に使うものは冗長でも保存したりするとか例外的なパターンもありますが、まずは基本形は上記のようなものだと理解して欲しいです。

2023-04-26 03:47 UTC, u1tnk commented on 08.ls_object/file_detail.rb
> +    @type = (state.ftype[0] == 'f' ? '-' : state.ftype[0])
改善はしたのですがちょっと違います。
インスタンス変数に保存して attr_readerを作るのは

- initializeがこみあうので見づらい
- インスタンス変数に一回保存するのでほんの少しだけですが無駄。
- そもそも attr_readerは getするメソッドを作るときのsyntax sugar(書きやすくするだけのもの)で、そのためにインスタンス変数に保存するのは手段と目的が違う。

ということなので、インスタンス変数は作らず、 typeなどのメソッドを作ってその中で計算したものを直接返すようにしましょう。

2023-04-26 07:57 UTC, nishitatsu-dev commented on 08.ls_object/file_detail.rb
> +    @type = (state.ftype[0] == 'f' ? '-' : state.ftype[0])
他のクラスも合わせて、attr_readerを無くし、メソッドで書き直しました。

2023-04-26 11:50 UTC, u1tnk requested changes

2023-04-26 11:50 UTC, u1tnk commented on 08.ls_object/test/list_provider_test.rb
> +  # def setup
ここはなぜコメントアウトしてるんでしょうか？

2023-04-26 11:50 UTC, u1tnk commented on 08.ls_object/option_long_formatter.rb
> +    @files.each do |file|
eachでとりあえずなんでもできるのですが、もっと便利なメソッドがたくさんあるので ArrayやEnumerableのドキュメントを見て工夫してみてください。

2023-04-26 11:50 UTC, u1tnk commented on 08.ls_object/option_long_formatter.rb
> +  def calc_text_field_width(files_with_detail)
ここも計算して保存するのではなく必要な情報を適宜計算するようにした方がスッキリしますね。
一例ですが、「:linkを引数で渡すと:linkの最大値を取ってくる」ようにすれば良いです。

2023-04-26 11:50 UTC, u1tnk commented on 08.ls_object/option_long_formatter.rb
> +      link = n.link.rjust(@widths[:link]).insert(-1, ' ')
n.linkで取ってこれるようにしたので link変数に入れる必要が無いのではと思います。
また、このままにするしても linkという名前だとフォーマット済みの文字列というのは直感的では無いので名前は変更が必要ですね。

2023-04-26 11:50 UTC, u1tnk commented on 08.ls_object/option_long_formatter.rb
> +      lines << type + permission + link + user + group + size + month + day + time + name
色々方法はありますが、 `"#{xxx} ....."` のような記法を使うともうちょっと見やすくなるかなと思います。

2023-04-27 07:08 UTC, nishitatsu-dev commented on 08.ls_object/normal_formatter.rb
> +  attr_reader :lines
すみません、漏れていました。削除しました。

2023-04-27 07:30 UTC, nishitatsu-dev commented on 08.ls_object/test/list_provider_test.rb
> +  # def setup
深い理由は無いのですが、下記の経緯です。コメントアウトを外しました。
1. テスト用のファイル類を作ってテストしています。
2. テスト用のファイル類はアップロードしないことにしました。変更入った時などに邪魔かな？と思ったので。
3. そのままでテスト出来ない部分（テスト用ファイルが必要な部分）をコメントアウトしておくことにしました。
4. コードの修正を繰り返す内に、他のテストではコメントアウトを外してアップロードしていました。
   このファイルは、当初の名残りです。他のテストに合わせて、コメントアウト外すことにします。

2023-04-27 07:33 UTC, nishitatsu-dev commented on 08.ls_object/display_formatter.rb
> +    @form = options[:l] ? OptionLongFormatter.new(files) : NormalFormatter.new(files)
formatterに修正しました。
（下記の指摘から、LSクラスに移動して修正しています。）

2023-04-27 07:34 UTC, nishitatsu-dev commented on 08.ls_object/display_formatter.rb
> +class DisplayFormatter
LSクラスに移動させました。

2023-04-27 07:34 UTC, nishitatsu-dev commented on 08.ls_object/option_long_formatter.rb
> +    @files.each do |file|
mapで書き直しました。

2023-04-27 07:35 UTC, nishitatsu-dev commented on 08.ls_object/option_long_formatter.rb
> +  def calc_text_field_width(files_with_detail)
指摘いただいた形になるように修正しました。

2023-04-27 07:40 UTC, nishitatsu-dev commented on 08.ls_object/option_long_formatter.rb
> +      link = n.link.rjust(@widths[:link]).insert(-1, ' ')
下記の指摘と合わせて修正しました。
（前半部分と後半部分に分けて作り、つなげて保存する形にしました。）

2023-04-27 07:41 UTC, nishitatsu-dev commented on 08.ls_object/option_long_formatter.rb
> +      lines << type + permission + link + user + group + size + month + day + time + name
指摘いただいた形で書き直しました。

2023-04-27 14:43 UTC, u1tnk commented on 08.ls_object/test/list_provider_test.rb
> +  # def setup
テストファイルは必須ではないので、厳しくは見ないです。
ということで不要と判断したら削除してコミットしないようにした方が良いですよ。

2023-04-27 14:56 UTC, u1tnk requested changes
だいぶスッキリしましたね。
あとはちょっと細かいところだけです！ 💪

2023-04-28 06:11 UTC, nishitatsu-dev commented on 08.ls_object/test/list_provider_test.rb
> +  # def setup
該当するファイルをコミットから除外しました。

2023-04-28 06:21 UTC, nishitatsu-dev commented on 08.ls_object/option_long_formatter.rb
> +      lines << first_half + second_half
line変数を作る方法で修正しました。（下記の経緯で、メソッドを書き直しました。）
1. 1行で書くと「長い」とRubocopから指摘されるので、line変数を作る方法にしました。
1. 「行数が多い」とRubocopから指摘されたので「各ファイル情報の部分」を別メソッドに切り出しました。
   その際、「blockの合計計算部分」を分けて書き直しました。

2023-04-28 06:40 UTC, nishitatsu-dev commented on 08.ls_object/option_long_formatter.rb
> +    lengths = @files_with_detail.map { |n| n.method(item).call.length }
すみません、「以前の書き方に対する修正方法」のコメントだと思ったのですが、念の為1行に書き直しました。
（「今の書き方に対する修正方法」の場合、イメージが合ってない気がするのですが、色々試してうまく行った書き方です）

2023-04-28 14:42 UTC, u1tnk approved these changes
二点指摘しましたが、修正必須では無いので合格です 🙆‍♀️

2023-04-28 14:42 UTC, u1tnk commented on 08.ls_object/option_long_formatter.rb
> +    @files_with_detail.map { |n| n.method(item).call.length }.max
ああ、惜しい！
さすがに書いちゃうと

`@files_with_detail.max { |n| n.method(item).call.length }`

ということです。 maxにブロックを渡せるというのはこういう意味です。

2023-04-28 14:42 UTC, u1tnk commented on 08.ls_object/option_long_formatter.rb
> +      line += "#{n.link.rjust(length_link)} "
現状で良いんですが、 一行にしたので、

`line += "#{n.link.rjust(calc_max_length(:link))} "`

こうしても大丈夫ですね。

2023-04-29 07:23 UTC, nishitatsu-dev commented on 08.ls_object/option_long_formatter.rb
> +    @files_with_detail.map { |n| n.method(item).call.length }.max
すみません、手元で試した所うまく動作せず、確認していただけないでしょうか🙇🏻
（文字数のデータが欲しい部分で、FileDetailオブジェクトが返ってきています。）

2023-04-29 07:30 UTC, nishitatsu-dev commented on 08.ls_object/option_long_formatter.rb
> +      line += "#{n.link.rjust(length_link)} "
ありがとうございます。

2023-04-30 14:12 UTC, u1tnk commented on 08.ls_object/option_long_formatter.rb
> +    @files_with_detail.map { |n| n.method(item).call.length }.max
あぁー、ちょっと勘違いしてました。すみません。
lengthが一番大きいところの FileDetailオブジェクト になっちゃいますね。失礼しました 🙏 
そこで length出せば取れますが、このケースだと元のmapしてmaxにする方がシンプルですね。元のままで大丈夫です 🙆‍♀️

2023-05-01 01:30 UTC, nishitatsu-dev commented on 08.ls_object/option_long_formatter.rb
> +    @files_with_detail.map { |n| n.method(item).call.length }.max
ご確認ありがとうございます🙏

2023-05-01 01:33 UTC, merged

2023-05-01 01:34 UTC, nishitatsu-dev commented
ありがとうございました！！！